// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $Role = {
  "user": $.$expr_Literal<$Role>;
  "assistant": $.$expr_Literal<$Role>;
} & $.EnumType<"default::Role", ["user", "assistant"]>;
const Role: $Role = $.makeType<$Role>(_.spec, "5408f6ba-6451-11ef-95cd-d741bfc91278", _.syntax.literal);

export type $Topic = {
  "LOVE": $.$expr_Literal<$Topic>;
  "CAREER": $.$expr_Literal<$Topic>;
  "GENERAL": $.$expr_Literal<$Topic>;
  "QUESTION": $.$expr_Literal<$Topic>;
} & $.EnumType<"default::Topic", ["LOVE", "CAREER", "GENERAL", "QUESTION"]>;
const Topic: $Topic = $.makeType<$Topic>(_.spec, "5409052e-6451-11ef-86bb-310464e95599", _.syntax.literal);

export type $MessageλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "role": $.PropertyDesc<$Role, $.Cardinality.One, false, false, false, false>;
  "topic": $.PropertyDesc<$Topic, $.Cardinality.One, false, false, false, false>;
  "<messages[is User]": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<messages": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Message = $.ObjectType<"default::Message", $MessageλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Message = $.makeType<$Message>(_.spec, "5409171c-6451-11ef-af9d-176614d6bf9c", _.syntax.literal);

const Message: $.$expr_PathNode<$.TypeSet<$Message, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Message, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "messages": $.LinkDesc<$Message, $.Cardinality.Many, {}, false, false,  false, false>;
  "characterTraits": $.PropertyDesc<$.ArrayType<_std.$str>, $.Cardinality.One, false, false, false, false>;
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "540aae6a-6451-11ef-b62c-f55ab50a5757", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { Role, Topic, $Message, Message, $User, User };

type __defaultExports = {
  "Role": typeof Role;
  "Topic": typeof Topic;
  "Message": typeof Message;
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "Role": Role,
  "Topic": Topic,
  "Message": Message,
  "User": User
};
export default __defaultExports;
